### ISSUE TITLE
Token says on crit ? 

### ISSUE THREAD

**Issue by Steelskinz** [napolitanod/Token-Says#63]
I was wondering if it will be available to use Token says when you score a natural 20 or natural 1 ?

**Comment by napolitanod** [comment]
Sorry for the delay - I'm in the process of buying a house so my time is very limited. I can certainly look into this but it will be delayed a bit. Such functionality would be system specific - Is this for DND5e? You might also check out midiQol custom sounds to see if that might solve this. Not sure if they get into the crit/fail granularity with the custom sounds but midiQol is much more system specific so has ready access to all of the data points needed.

**Comment by Steelskinz** [comment]
Oh it's fine don't worry, I was just wondering that's it ! Take your time, you did already a good job on the module i'll check it out ! Good luck for your house !

**Comment by Armandeus66** [comment]
For when you have time, of course... I really appreciate this module and your work, Napolitanod!

I'd like to add to this request and ask for support for Pathfinder 2nd Edition critical success/failure. It isn't dependent on 1s and 20s, but instead occurs at a roll that is +/-10 from the target number. It is complicated because a 1 or 20 further down/upgrades a failure/success to critical. However, I see that the Foundry PF2E system marks rolls in chat as "critical success, success, failure, critical failure" with text. Perhaps Token Says could look for this text as a trigger? I can't remember whether D&D5E prints "critical" to chat, but if it does, perhaps that might be a way to simplify the detection of criticals over different systems.

There are other modules (Maestro, Dice So Nice, etc.) that detect 1 or 20 and play a sound or something, but currently nothing that does so for the PF2E system to include rolls that are not combat attacks but are instead skill checks. If Token Says could do this, then much of what those other modules (Maestro's combat and hype tracks too) could be covered by Token Says, and we would need less modules to do these things, plus the ability of Token Says to do more than sound.

Thanks again!

**Comment by napolitanod** [comment]
Release 1.9.2 should now support critical hits and fumbles/critical misses for pf2e and dnd5e. 

- For dnd5e you must have midiQol installed given the complications involved with factoring what /when something is actually critical hit. 
- For pf2e, the critical hit only triggers once the critical damage is applied. The critical miss occurs with the attack roll.

1.9.2 also includes the ability to execute a macro when a saying is triggered, so may be some fun additional stuff you can make happen there.

Please let me know if anything looks amiss/doesn't work.

**Comment by Armandeus66** [comment]
Thank you very much for adding this!

May I ask, are non-attack critical successes and failures (skill checks) also supported?

**Comment by napolitanod** [comment]
How do critical success and failures work for skills within Foundry? I can see where to roll the skill but where is the target number defined during the roll in order to compare against?

**Comment by Armandeus66** [comment]
Hi.

If there is no targeted token, then the GM assigns the DC number to roll for, and there will be no indication in-game of what it is.

However, if a token is targeted, the DC will be automatically assigned by the system for the roll. You can see this if you target an actor and try, for example, an Intimidation check (the DC will be based on the skill-using character's intimidation skill) or a spell that requires a saving throw (the number will be determined based on the target's Will, Reflex, or Fortitude number).  Some saves depend on the caster's spell DC. I think that in these cases, the target number is included in the roll dialogue, and a result from critical success through critical failure will be printed to the chat window.

**Comment by napolitanod** [comment]
The data.flags.pf2e.context.outcome is what I am looking at. The problem I am having is that I cannot get a target number to come up for skills. Perhaps you can tell me the steps to follow as I am unfamiliar with the pf2e rules and interface. Here is what I am doing:

- Signed in as GM
- Using 'Ezren (Beginners Box)' PC
- Target an 'Ancient Forest Dragon'
- Open the Ezren character sheet
- Select the Proficiencies tab
- Click the +0 next to 'Survival'
- Roll dialog pops up with options. I don't see a target number shown here. I click 'Roll (+0)' button
- The roll occurs and chat message shows result, in this case a 2. The chat does not indicate the target number or if I succeeded or failed.

**Comment by Armandeus66** [comment]
Survival is not something you would target a token for. A good choice would be Intimidate.

Another way to get good examples of skill and spell rolls that would give you what you need is to use actions or spells. They should already be some on the pregenerated characters. Put both of the actors in the combat tracker and try a few. Many will have descriptions (click the name) which explain what skill or save will be used. Using actions and spells on a target when both are in the combat tracker should give you a dialog for rolling that is explanatory, as well as a chat card result telling the degree of success.

**Comment by napolitanod** [comment]
I pushed out 1.9.3 which adds to PF2e saves, ability checks, critical success skills, critical failure skills. Not sure every circumstance that these are triggered will be captured but works for those scenarios that I tested.

**Comment by Armandeus66** [comment]
Thank you! I'm looking forward to trying it out!

**Comment by Armandeus66** [comment]
I've set up a lot of audio sayings using Token Says and I plan to test it in my next session. Thanks again!

One thing I noticed is that Perception isn't listed under skill checks. It's off to the left side of the character sheet in PF2E so maybe you missed it. It's usually used for initiative rolls (which you have separately) and detecting hidden things, much like in D&D5E.

Is it correct to assume that to assign a saying to an action, you choose the skill associated with it and then type in the action? Some actions don't have skills associated with them. How would we trigger those? 

Also, how can I trigger when a spell is cast?

Thanks!

**Comment by Steelskinz** [comment]
( I finally got that account back kek. )
First of all thanks so much for your hardwork ! I really love the update and it works like it should, however, it seems that the " Respond " option  does not work with the Critical Hit / Fumble is it an impossible trigger to get ?

**Comment by napolitanod** [comment]
> ( I finally got that account back kek. ) First of all thanks so much for your hardwork ! I really love the update and it works like it should, however, it seems that the " Respond " option does not work with the Critical Hit / Fumble is it an impossible trigger to get ?

That should be possible, I must have a different branch in code for factoring responses that I missed the update on. I'm moving to new house this week so it may be a week or so before I can can it working. Thanks!

**Comment by napolitanod** [comment]
> I've set up a lot of audio sayings using Token Says and I plan to test it in my next session. Thanks again!
> 
> One thing I noticed is that Perception isn't listed under skill checks. It's off to the left side of the character sheet in PF2E so maybe it's easy to miss. It's usually used for initiative rolls (which you have defined separately) and detecting hidden things, much like in D&D5E.
> 
> Is it correct to assume that to assign a saying to an action, you choose the skill associated with it and then type in the action? Some actions don't have skills associated with them. How would we trigger (respond to) those?
> 
> Also, how can I trigger (or respond to) when a spell is cast?
> 
> What about healing? For example, what if I wanted a character to say "thank you" when receiving a Heal spell? There are lots of healing spells, so is it possible to trigger a saying responding to a "healing roll"?
> 
> Thanks! This module is lots of fun!

The 'Item Name' action type should pick up many of the actions that do not generate attacks. So non-attack spells rolled from sheet should trigger the Item Name action type if the chat data is being set consistently. 

Not sure why perception is missing - the options available come directly as a feed from the PF2E config for skills. They must have perception somewhere else, I'll dig into when I have a chance.

I'll have to look into how pf2e passes healing roll data. If it is flagged in a generic way then I should be able to create a generic approach for handling healing like I do damage. The module relies on consistency in a system's setting of chat data/flags and I've seen some systems be less standardized with how they set chat data (not saying pf2e is one, just in general) so I may hit some limitations on things.

**Comment by napolitanod** [comment]
I added perception as an option within pf2e skills to the most recent release. It seems pf2e, at least the system, doesn't consider perception a skill so this had to be appended. 

There's another open item for handling healing/damage, so I'm going to close this ticket because I think everything else on it has been addressed
